name: green_flux_assessment
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  dynamic_color: ^1.6.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  go_router: ^12.0.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  maps_launcher: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  mockito: ^5.4.2
  integration_test:
    sdk: flutter
  mocktail: ^1.0.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - .env
